{{- if .Values.deployment.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "relayer.fullname" . }}
  labels:
    {{- include "relayer.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/search: "true"
    datree.skip/DEPLOYMENT_INCORRECT_REPLICAS_VALUE: only require 1 relayer
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "relayer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "relayer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ .Values.deployment.serviceAccountName }}"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.firehoseTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/app/fireantelope"
            - "start"
            - "relayer"
            - "--config-file="
            - "--log-format=stackdriver"
            - "--log-to-file=false"
            - "--common-one-block-store-url={{ .Values.global.store.commonOneBlockStoreUrl }}"
            - "--relayer-max-source-latency={{ .Values.deployment.relayerMaxSourceLatency }}"
            - "--relayer-grpc-listen-addr={{ .Values.deployment.relayerGrpcListenAddr }}"
            - "--relayer-source={{ .Values.deployment.relayerSource1 }}"
            {{- if .Values.deployment.relayerSource2 }}
            - "--relayer-source={{ .Values.deployment.relayerSource2 }}"
            {{- end }}
            {{- with .Values.deployment.extraCommands }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.deployment.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.localVolume.enabled }}
          volumeMounts:
            {{- toYaml .Values.localVolume.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.localVolume.enabled }}
      volumes:
        {{- toYaml .Values.localVolume.volume | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Chart.Name }}
                topologyKey: kubernetes.io/hostname
{{- end }}