---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "relayer.fullname" . }}
  labels:
    {{- include "relayer.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "relayer.selectorLabels" . | nindent 6 }}
