stages:
  - lint
  - test
  - release

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

always-run:
  script: echo "$CI_PIPELINE_SOURCE"
  
include:
  - charts/firehose-antelope/.gitlab-ci.yml