# Default values for blockchain-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "quay.io/ultra.io/firehose-antelope"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: merger

statefulset:
  enabled: true
  serviceAccountName: ""
  # commands
  mergerGrpcListenAddr: :9000
  mergerPruneForkedBlocksAfter: 2000
  mergerStopBlock: 0
  mergerTimeBetweenStoreLookups: 5s
  extraCommands: []
  # env
  env:
    - name: INFO
      value: ".*"
  # ports
  ports:
    - containerPort: 9000
      name: grpc-endpoint
      protocol: TCP
    - containerPort: 9102
      name: prometheus
      protocol: TCP
  storageLimit: 4Gi
  storageSize: 1Gi
  persistentVolumeClaimEnabled: true
  dataVolumeMount:
    - mountPath: "/nodeos-data"
      name: datadir

# For local test
localVolume:
  enabled: false
  volumeMounts:
    - mountPath: "/storage"
      name: storage
  volume:
    - name: storage
      persistentVolumeClaim:
        claimName: storage-pvc

### Note: First port in list will be used as an Ingress port!
service:
  labels:
    monitoring: "true"
    monitor: prometheus
  type: ClusterIP
  ports:
    - protocol: TCP
      name: grpc-endpoint
      port: 9000
      targetPort: 9000
    - protocol: TCP
      name: prometheus
      port: 9102
      targetPort: 9102

livenessProbe:
  # httpGet:
  #   path: /explorer/payment/v1/health
  #   port: http
  # initialDelaySeconds: 60
  # periodSeconds: 3

readinessProbe:
  # httpGet:
  #   path: /explorer/payment/v1/ready
  #   port: http
  # initialDelaySeconds: 8
  # periodSeconds: 3

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi

pdb:
  maxUnavailable: 70%

nodeSelector:
  role: application
