global:
  image:
    repository: quay.io/ultra.io/firehose-antelope
    pullPolicy: IfNotPresent
    firehoseTag: v1.4.1-1.0.2
    nodeosTag: v1.4.1-1.0.2-nodeos3.2.5-2.0.4

  nodeos:
    apis: []
    genesis_json: {}

  store:
    commonOneBlockStoreUrl: ""
    commonMergedBlocksStoreUrl: ""
    commonForkedBlocksStoreUrl: ""
    substreamsStateStoreUrl: "/firehose-data/localdata"
    

serviceMonitor:
  enabled: false
  name: ""
  spec: {}
serviceAccount:
  enabled: false
  writerName: ""
  writerAnnotations: {}
  readerName: ""
  readerAnnotations: {}
# Only enable if testing locally
persistentVolumeEnabled: false
