serviceMonitor:
  enabled: false
  name: ""
  spec: {}
serviceAccount:
  enabled: false
  writerName: ""
  writerAnnotations: {}
  readerName: ""
  readerAnnotations: {}
# Only enable if testing locally
persistentVolumeEnabled: false
