apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reader-node.fullname" . }}
  labels:
    {{- include "reader-node.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configmap.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reader-node.fullname" . }}-protocol-features
  labels:
    {{- include "reader-node.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configmap.protocol_features }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}