---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "reader-node.fullname" . }}
  labels:
    {{- include "reader-node.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "reader-node.selectorLabels" . | nindent 6 }}
