{{- if .Values.statefulset.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "reader-node.fullname" . }}
  labels:
    {{- include "reader-node.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/search: "true"
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "reader-node.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "reader-node.name" . }}
  template: 
    metadata:
      labels:
        {{- include "reader-node.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ .Values.statefulset.serviceAccountName }}"
      containers:
        - name: "{{ .Values.statefulset.name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/app/fireantelope"
            - "start"
            - "reader-node"
            - "--config-file="
            - "--log-format=stackdriver"
            - "--log-to-file=false"
            - "--common-one-block-store-url={{ .Values.statefulset.oneBlockStoreURL }}"
            - "--common-system-shutdown-signal-delay=20s"
            - "--reader-node-arguments={{ .Values.statefulset.nodeosArguments }}"
            - "--reader-node-blocks-chan-capacity=100"
            - "--reader-node-data-dir=/nodeos-data"
            - "--reader-node-debug-firehose-logs=false"
            - "--reader-node-grpc-listen-addr=:9000"
            - "--reader-node-manager-api-addr=:8080"
            - "--reader-node-path=nodeos"
            - "--reader-node-readiness-max-latency=5s"
            - "--reader-node-start-block-num=0"
            - "--reader-node-stop-block-num=0"
            - "--reader-node-working-dir=/nodeos-data/reader/work"
            - "--common-auto-mem-limit-percent={{ .Values.statefulset.autoMemLimitPercent }}"
          {{- with .Values.statefulset.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.statefulset.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.statefulset.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      terminationGracePeriodSeconds: 60
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "reader-node.fullname" . }}
          name: configdir
        - configMap:
            defaultMode: 420
            name: {{ include "reader-node.fullname" . }}-protocol-features
          name: etc-nodeos-protocolfeatures
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        annotations:
          resize.topolvm.io/storage_limit: {{ .Values.statefulset.storageLimit }}
        name: datadir
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.statefulset.storageSize }}
        storageClassName: gcpssd-lazy
        volumeMode: Filesystem
      status:
        phase: Pending
{{ end }}