# Default values for blockchain-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "quay.io/ultra.io/firehose-antelope"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: relayer

deployment:
  enabled: true
  serviceAccountName: ""
  # commands
  commonOneBlockStoreUrl: ""
  relayerMaxSourceLatency: 10m
  relayerGrpcListenAddr: :9000
  relayerSource1: dns:///reader-node-0.reader-node:9000
  relayerSource2: dns:///reader-node-1.reader-node:9000
  extraCommands: []
  # ports
  ports:
    - name: publisher
      containerPort: 9000
      protocol: TCP
    - name: prometheus
      containerPort: 9102
      protocol: TCP
  # env
  env:
    - name: INFO
      value: github.com/dfuse-io/.*

# For local test
localVolume:
  enabled: false
  volumeMounts:
    - mountPath: "/storage"
      name: storage
  volume:
    - name: storage
      persistentVolumeClaim:
        claimName: storage-pvc

### Note: First port in list will be used as an Ingress port!
service:
  labels:
    monitoring: "true"
  type: ClusterIP
  ports:
    - protocol: TCP
      name: publisher
      port: 9000
      targetPort: 9000
    - protocol: TCP
      name: prometheus
      port: 9102
      targetPort: 9102
  

livenessProbe:
  # httpGet:
  #   path: /explorer/payment/v1/health
  #   port: http
  # initialDelaySeconds: 60
  # periodSeconds: 3

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 5
  successThreshold: 1
  tcpSocket:
    port: 9000
  timeoutSeconds: 1

resources:
  limits:
    cpu: 1
    memory: 1500Mi
  requests:
    cpu: 200m
    memory: 600Mi

pdb:
  minAvailable: 1

nodeSelector:
