{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.serviceMonitor.name }}
  labels:
    {{- include "firehose-antelope.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.serviceMonitor.spec | nindent 2 }}
{{ end }}