{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.writerName }}
  labels:
    {{- include "firehose-antelope.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.writerAnnotations | nindent 4 }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.readerName }}
  labels:
    {{- include "firehose-antelope.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.readerAnnotations | nindent 4 }}
{{ end }}