apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-blocks-writer
  labels:
    {{- include "firehose-antelope.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: app-blocks-writer@dfuse-302310.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-data-reader
  labels:
    {{- include "firehose-antelope.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: app-data-reader@dfuse-302310.iam.gserviceaccount.com