{{- if .Values.ingress.enabled -}}
{{- $fullName := include "firehose-antelope.fullname" . -}}
{{- $labels := include "firehose-antelope.labels" . -}}

{{- range .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-{{ .secretName }}
  labels:
    {{- $labels | nindent 4 }}  
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""
---
{{- end }}
{{- end }}