apiVersion: v1
kind: Service
metadata:
  name: {{ include "merger.fullname" . }}
  labels:
    {{- with .Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "merger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "merger.selectorLabels" . | nindent 4 }}
  clusterIP: None
