{{- if .Values.statefulset.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "merger.fullname" . }}
  labels:
    {{- include "merger.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/search: "true"
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "merger.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "merger.name" . }}
  template: 
    metadata:
      labels:
        {{- include "merger.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ .Values.statefulset.serviceAccountName }}"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.firehoseTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command:
            - "/app/fireantelope"
            - "start"
            - "merger"
            - "--config-file="
            - "--log-format=stackdriver"
            - "--log-to-file=false"
            - "--common-merged-blocks-store-url={{ .Values.global.store.commonMergedBlocksStoreUrl }}"
            - "--common-one-block-store-url={{ .Values.global.store.commonOneBlockStoreUrl }}"
            - "--common-forked-blocks-store-url={{ .Values.global.store.commonForkedBlocksStoreUrl }}"
            - "--merger-grpc-listen-addr={{ .Values.statefulset.mergerGrpcListenAddr }}"
            - "--merger-prune-forked-blocks-after={{ .Values.statefulset.mergerPruneForkedBlocksAfter }}"
            - "--merger-stop-block={{ .Values.statefulset.mergerStopBlock }}"
            - "--merger-time-between-store-lookups={{ .Values.statefulset.mergerTimeBetweenStoreLookups }}"
            {{- with .Values.statefulset.extraCommands }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.statefulset.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.statefulset.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.statefulset.persistentVolumeClaimEnabled }}
            {{- toYaml .Values.statefulset.dataVolumeMount | nindent 12 }}
          {{- end }}
          {{- if .Values.localVolume.enabled }}
            {{- toYaml .Values.localVolume.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.localVolume.enabled }}
      volumes:
        {{- toYaml .Values.localVolume.volume | nindent 8 }}
      {{- end }}
      nodeSelector:
        role: application
        pool: {{ .Values.global.nodePool }}
  {{- if .Values.statefulset.persistentVolumeClaimEnabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        annotations:
          resize.topolvm.io/storage_limit: {{ .Values.statefulset.storageLimit }}
        name: datadir
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.statefulset.storageSize }}
        storageClassName: gcpssd-lazy
        volumeMode: Filesystem
      status:
        phase: Pending
  {{- end}}
{{- end }}