# Default values for blockchain-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: "quay.io/ultra.io/firehose-antelope"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: reader-node

statefulset:
  enabled: true
  name: nodeos
  serviceAccountName: ""
  # commands
  commonOneBlockStoreUrl: ""
  commonSystemShutdownSignalDelay: 20s
  readerNodeArguments: '--config-dir=/etc/nodeos --data-dir=/nodeos-data --genesis-json=/etc/nodeos/genesis.json'
  readerNodeBlocksChanCapacity: 100
  readerNodeDataDir: /nodeos-data
  readerNodeDebugFirehoseLogs: false
  readerNodeGrpcListenAddr: :9000
  readerNodeManagerApiAddr: :8080
  readerNodePath: nodeos
  readerNodeReadinessMaxLatency: 5s
  readerNodeStartBlockNum: 0
  readerNodeStopBlockNum: 0
  readerNodeWorkingDir: /nodeos-data/reader/work
  commonAutoMemLimitPercent: 90
  extraCommands: []
  # Others
  env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: INFO
      value: ".*"
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: PITREOS_THREADS
      value: '4'
  ports:
    - containerPort: 8080
      name: manageos-http
      protocol: TCP
    - containerPort: 9876
      name: nodeos-p2p
      protocol: TCP
    - containerPort: 9102
      name: prometheus
      protocol: TCP
    - containerPort: 9000
      name: publisher
      protocol: TCP
  volumeMounts:
    - mountPath: "/etc/nodeos"
      name: configdir
    - mountPath: "/etc/nodeos/protocol_features"
      name: etc-nodeos-protocolfeatures
  storageSize: 10Gi
  storageLimit: 40Gi
  persistentVolumeClaimEnabled: true
  dataVolumeMount:
    - mountPath: "/nodeos-data"
      name: datadir

# For local test
localVolume:
  enabled: false
  volumeMounts:
    - mountPath: "/storage"
      name: storage
  volume:
    - name: storage
      persistentVolumeClaim:
        claimName: storage-pvc

### Note: First port in list will be used as an Ingress port!
service:
  labels:
    monitoring: "true"
  type: ClusterIP
  ports:
    - protocol: TCP
      name: prometheus
      port: 9102
      targetPort: 9102
    - protocol: TCP
      name: publisher
      port: 9000
      targetPort: 9000

readinessProbe:
  failureThreshold: 1
  httpGet:
    path: "/healthz"
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 1Gi

pdb:
  minAvailable: 1

nodeSelector:
  role: application

configmap:
  config:
    config.ini: |
      http-server-address = 0.0.0.0:8888
      p2p-server-address = 0.0.0.0:9876
      p2p-max-nodes-per-host = 2
      connection-cleanup-period = 60
      verbose-http-errors = true
      chain-state-db-size-mb = 64000
      http-validate-host = false
      max-transaction-time = 5000
      abi-serializer-max-time-ms = 500000

      plugin = eosio::net_api_plugin
      plugin = eosio::chain_api_plugin
      plugin = eosio::db_size_api_plugin
      plugin = eosio::producer_api_plugin

      # Max speed for replay
      validation-mode = light

      # Enable deep mind
      deep-mind = true
      agent-name = reader-node
      p2p-peer-address = 127.0.0.1:9876

      wasm-runtime = eos-vm-jit
      eos-vm-oc-enable = true
      eos-vm-oc-compile-threads = 4
      contracts-console = true
      read-mode = head
      p2p-accept-transactions = false
      api-accept-transactions = false

      http-threads = 2
    genesis.json: |
      {
        "initial_timestamp": "2018-09-01T12:00:00.000",
        "initial_key": "EOS7qBcTsKhCfUeGpn15JTtwrjEnZfXzeCDLnF1LtKr6xnMAr4b5k",
        "initial_configuration": {
          "max_block_net_usage": 1048576,
          "target_block_net_usage_pct": 1000,
          "max_transaction_net_usage": 524288,
          "base_per_transaction_net_usage": 12,
          "net_usage_leeway": 500,
          "context_free_discount_net_usage_num": 20,
          "context_free_discount_net_usage_den": 100,
          "max_block_cpu_usage": 400000,
          "target_block_cpu_usage_pct": 1000,
          "max_transaction_cpu_usage": 300000,
          "min_transaction_cpu_usage": 100,
          "ultra_veto_enabled": 1,
          "max_transaction_lifetime": 3600,
          "deferred_trx_expiration_window": 600,
          "max_transaction_delay": 3888000,
          "max_inline_action_size": 524287,
          "max_inline_action_depth": 10,
          "max_authority_depth": 10
        }
      }
  protocol_features:
    BUILTIN-ACTION_RETURN_VALUE.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "69b064c5178e2738e144ed6caa9349a3995370d78db29e494b3126ebd9111966",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "ACTION_RETURN_VALUE"
      }
    BUILTIN-ASSERT_CODE_NAME_WHAT_MESSAGE.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "86f62fe597c7ddb18e14477bb2429eb1ee6c296a47bf8f7240aff6944166ff6c",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "ASSERT_CODE_NAME_WHAT_MESSAGE"
      }
    BUILTIN-BILL_FAILED_TRANSACTIONS.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "f0053bba76d93f1e5434c1cf87fa45f9e3f2e0dd0074f9183a5ac8a33b601dde",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "BILL_FAILED_TRANSACTIONS"
      }
    BUILTIN-BLOCKCHAIN_PARAMETERS.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "70787548dcea1a2c52c913a37f74ce99e6caae79110d7ca7b859936a0075b314",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "BLOCKCHAIN_PARAMETERS"
      }
    BUILTIN-CONFIGURABLE_WASM_LIMITS2.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "8139e99247b87f18ef7eae99f07f00ea3adf39ed53f4d2da3f44e6aa0bfd7c62",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "CONFIGURABLE_WASM_LIMITS2"
      }
    BUILTIN-CRYPTO_PRIMITIVES.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "68d6405cb8df3de95bd834ebb408196578500a9f818ff62ccc68f60b932f7d82",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "CRYPTO_PRIMITIVES"
      }
    BUILTIN-DISABLE_DEFERRED.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "086466d278efe08d9be42a547a2bb8e93b9f3092befbd2042683cad6d17805dd",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "DISABLE_DEFERRED"
      }
    BUILTIN-DISALLOW_EMPTY_PRODUCER_SCHEDULE.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "2853617cec3eabd41881eb48882e6fc5e81a0db917d375057864b3befbe29acd",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "DISALLOW_EMPTY_PRODUCER_SCHEDULE"
      }
    BUILTIN-FIX_LINKAUTH_RESTRICTION.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "a98241c83511dc86c857221b9372b4aa7cea3aaebc567a48604e1d3db3557050",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "FIX_LINKAUTH_RESTRICTION"
      }
    BUILTIN-FORWARD_SETCODE.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "898082c59f921d0042e581f00a59d5ceb8be6f1d9c7a45b6f07c0e26eaee0222",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "FORWARD_SETCODE"
      }
    BUILTIN-GET_BLOCK_NUM.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "e5d7992006e628a38c5e6c28dd55ff5e57ea682079bf41fef9b3cced0f46b491",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "GET_BLOCK_NUM"
      }
    BUILTIN-GET_CODE_HASH.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "d2596697fed14a0840013647b99045022ae6a885089f35a7e78da7a43ad76ed4",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "GET_CODE_HASH"
      }
    BUILTIN-GET_SENDER.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "1eab748b95a2e6f4d7cb42065bdee5566af8efddf01a55a0a8d831b823f8828a",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "GET_SENDER"
      }
    BUILTIN-NO_DUPLICATE_DEFERRED_ID.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [
          "ef43112c6543b88db2283a2e077278c315ae2c84719a8b25f25cc88565fbea99"
        ],
        "description_digest": "45967387ee92da70171efd9fefd1ca8061b5efe6f124d269cd2468b47f1575a0",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "NO_DUPLICATE_DEFERRED_ID"
      }
    BUILTIN-ONLY_BILL_FIRST_AUTHORIZER.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "2f1f13e291c79da5a2bbad259ed7c1f2d34f697ea460b14b565ac33b063b73e2",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "ONLY_BILL_FIRST_AUTHORIZER"
      }
    BUILTIN-ONLY_LINK_TO_EXISTING_PERMISSION.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "f3c3d91c4603cde2397268bfed4e662465293aab10cd9416db0d442b8cec2949",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "ONLY_LINK_TO_EXISTING_PERMISSION"
      }
    BUILTIN-PREACTIVATE_FEATURE.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "64fe7df32e9b86be2b296b3f81dfd527f84e82b98e363bc97e40bc7a83733310",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": false,
          "enabled": true
        },
        "builtin_feature_codename": "PREACTIVATE_FEATURE"
      }
    BUILTIN-RAM_RESTRICTIONS.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "1812fdb5096fd854a4958eb9d53b43219d114de0e858ce00255bd46569ad2c68",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "RAM_RESTRICTIONS"
      }
    BUILTIN-REPLACE_DEFERRED.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "9908b3f8413c8474ab2a6be149d3f4f6d0421d37886033f27d4759c47a26d944",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "REPLACE_DEFERRED"
      }
    BUILTIN-RESTRICT_ACTION_TO_SELF.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "e71b6712188391994c78d8c722c1d42c477cf091e5601b5cf1befd05721a57f3",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "RESTRICT_ACTION_TO_SELF"
      }
    BUILTIN-WEBAUTHN_KEY.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "927fdf78c51e77a899f2db938249fb1f8bb38f4e43d9c1f75b190492080cbc34",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "WEBAUTHN_KEY"
      }
    BUILTIN-WTMSIG_BLOCK_SIGNATURES.json: |
      {
        "protocol_feature_type": "builtin",
        "dependencies": [],
        "description_digest": "ab76031cad7a457f4fd5f5fca97a3f03b8a635278e0416f77dcc91eb99a48e10",
        "subjective_restrictions": {
          "earliest_allowed_activation_time": "1970-01-01T00:00:00.000",
          "preactivation_required": true,
          "enabled": true
        },
        "builtin_feature_codename": "WTMSIG_BLOCK_SIGNATURES"
      }
