{{- if .Values.backendConfig.enabled -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Chart.Name }}-bec-https
  labels:
    {{- include "substreams-tier1.labels" . | nindent 4 }}
spec:
  healthCheck:
    checkIntervalSec: 10
    port: 9000
    requestPath: /
    timeoutSec: 3
    type: HTTPS
  timeoutSec: 86400
{{- end }}
