apiVersion: v1
kind: Service
metadata:
  name: {{ include "substreams-tier1.fullname" . }}
  labels:
    {{- with .Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "substreams-tier1.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "substreams-tier1.selectorLabels" . | nindent 4 }}
