{{- if .Values.statefulset.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "substreams-tier1.fullname" . }}
  labels:
    {{- include "substreams-tier1.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/search: "true"
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "substreams-tier1.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "substreams-tier1.name" . }}
  template: 
    metadata:
      labels:
        {{- include "substreams-tier1.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ .Values.statefulset.serviceAccountName }}"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.nodeosTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command:
            - "/app/fireantelope"
            - "start"
            - "substreams-tier1"
            - "--config-file="
            - "--log-format=stackdriver"
            - "--log-to-file=false"
            - "--common-auth-plugin={{ .Values.statefulset.commonAuthPlugin }}"
            - "--common-live-blocks-addr={{ .Values.statefulset.commonLiveBlocksAddr }}"
            - "--common-system-shutdown-signal-delay={{ .Values.statefulset.commonSystemShutdownSignalDelay }}"
            - "--common-merged-blocks-store-url={{ .Values.statefulset.commonMergedBlocksStoreUrl }}"
            - "--common-one-block-store-url={{ .Values.global.store.commonOneBlockStoreUrl }}"
            - "--common-forked-blocks-store-url={{ .Values.statefulset.commonForkedBlocksStoreUrl }}"
            - "--substreams-state-bundle-size={{ .Values.statefulset.substreamsStateBundleSize }}"
            - "--substreams-state-store-url={{ .Values.global.store.substreamsStateStoreUrl }}"
            - "--substreams-state-store-default-tag={{ .Values.statefulset.substreamsStateStoreDefaultTag }}"
            - "--substreams-tier1-grpc-listen-addr={{ .Values.statefulset.substreamsTier1GrpcListenAddr }}"
            - "--substreams-tier1-subrequests-endpoint={{ .Values.statefulset.substreamsTier1SubrequestsEndpoint }}"
            - "--substreams-tier1-discovery-service-url={{ .Values.statefulset.substreamsTier1DiscoveryServiceUrl }}"
            - "--substreams-tier1-subrequests-insecure={{ .Values.statefulset.substreamsTier1SubrequestsInsecure }}"
            - "--substreams-tier1-subrequests-plaintext={{ .Values.statefulset.substreamsTier1SubrequestsPlaintext }}"
            - "--substreams-tier1-max-subrequests={{ .Values.statefulset.substreamsTier1MaxSubrequests }}"
            {{- with .Values.statefulset.extraCommands }}
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- with .Values.statefulset.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.statefulset.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.localVolume.enabled }}
          volumeMounts:
            {{- toYaml .Values.localVolume.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.localVolume.enabled }}
      volumes:
        {{- toYaml .Values.localVolume.volume | nindent 8 }}
      {{- end }}
{{- end }}
