# Default values for blockchain-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "quay.io/ultra.io/3rdparty-devtools"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: producer

statefulset:
  name: nodeos
  # Others  
  ports:
    - containerPort: 8888
      name: nodeos-http
      protocol: TCP
    - containerPort: 9876
      name: nodeos-p2p
      protocol: TCP

### Note: First port in list will be used as an Ingress port!
service:
  labels:
    monitoring: "true"
  type: ClusterIP
  ports:
    - protocol: TCP
      name: nodeos-http
      port: 8888
      targetPort: 8888
    - protocol: TCP
      name: nodeos-p2p
      port: 9876
      targetPort: 9876

resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 2
    memory: 2Gi

pdb:
  minAvailable: 1

nodeSelector:
  role: application
