apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: firehose-bec-https
  labels: 
    {{- include "firehose.labels" . | nindent 4 }}
spec:
  healthCheck:
    checkIntervalSec: 10
    port: 9000
    requestPath: /
    timeoutSec: 3
    type: HTTPS
  timeoutSec: 86400