---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "producer.fullname" . }}
  labels:
    {{- include "producer.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "producer.selectorLabels" . | nindent 6 }}
