# Default values for blockchain-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: "quay.io/ultra.io/firehose-antelope"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: firehose

statefulset:
  enabled: true
  serviceAccountName: ""
  # commands
  commonAuthPlugin: null://
  commonLiveBlocksAddr: dns:///relayer:9000
  commonSystemShutdownSignalDelay: 30s
  firehoseGrpcListenAddr: :9000
  extraCommands: []
  # ports
  ports:
    - name: grpc
      containerPort: 9000
      protocol: TCP
    - name: prometheus
      containerPort: 9102
      protocol: TCP
  # env
  env:
    - name: INFO
      value: github.com/dfuse-io/.*

# For local test
localVolume:
  enabled: false
  volumeMounts:
    - mountPath: "/storage"
      name: storage
  volume:
    - name: storage
      persistentVolumeClaim:
        claimName: storage-pvc

### Note: First port in list will be used as an Ingress port!
service:
  labels:
    monitoring: "true"
  type: ClusterIP
  ports:
    - protocol: TCP
      name: grpc
      port: 9000
      targetPort: 9000
    - protocol: TCP
      name: prometheus
      port: 9102
      targetPort: 9102

livenessProbe:
  # httpGet:
  #   path: /explorer/payment/v1/health
  #   port: http
  # initialDelaySeconds: 60
  # periodSeconds: 3

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: "/"
    port: 9000
    scheme: HTTPS
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 500Mi

autoscaling:
  enabled: false

nodeSelector:
  role: application
